# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_training.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("background-color: #696969;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("border: 1px solid white;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.header = QtWidgets.QLabel(self.main_frame)
        self.header.setGeometry(QtCore.QRect(14, 14, 1221, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"font-weight: bold;\n"
"")
        self.header.setObjectName("header")
        self.training_name_label = QtWidgets.QLabel(self.main_frame)
        self.training_name_label.setGeometry(QtCore.QRect(60, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.training_name_label.setFont(font)
        self.training_name_label.setStyleSheet("border: none;\n"
"color: white;")
        self.training_name_label.setObjectName("training_name_label")
        self.cost_label = QtWidgets.QLabel(self.main_frame)
        self.cost_label.setGeometry(QtCore.QRect(60, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cost_label.setFont(font)
        self.cost_label.setStyleSheet("border: none;\n"
"color: white;")
        self.cost_label.setObjectName("cost_label")
        self.datetime_label = QtWidgets.QLabel(self.main_frame)
        self.datetime_label.setGeometry(QtCore.QRect(430, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.datetime_label.setFont(font)
        self.datetime_label.setStyleSheet("border: none;\n"
"color: white;")
        self.datetime_label.setObjectName("datetime_label")
        self.department_label = QtWidgets.QLabel(self.main_frame)
        self.department_label.setGeometry(QtCore.QRect(430, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.department_label.setFont(font)
        self.department_label.setStyleSheet("border: none;\n"
"color: white;")
        self.department_label.setObjectName("department_label")
        self.date_pick = QtWidgets.QDateEdit(self.main_frame)
        self.date_pick.setGeometry(QtCore.QRect(430, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.date_pick.setFont(font)
        self.date_pick.setStyleSheet("color: white;\n"
"QCalendarWidget {\n"
"    background: white;\n"
"    color: black;\n"
"\n"
"}")
        self.date_pick.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 12, 10), QtCore.QTime(0, 0, 0)))
        self.date_pick.setCalendarPopup(True)
        self.date_pick.setObjectName("date_pick")
        self.brochure_label = QtWidgets.QLabel(self.main_frame)
        self.brochure_label.setGeometry(QtCore.QRect(860, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.brochure_label.setFont(font)
        self.brochure_label.setStyleSheet("border: none;\n"
"color: white;")
        self.brochure_label.setObjectName("brochure_label")
        self.max_participants_label = QtWidgets.QLabel(self.main_frame)
        self.max_participants_label.setGeometry(QtCore.QRect(220, 360, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.max_participants_label.setFont(font)
        self.max_participants_label.setStyleSheet("border: none;\n"
"color: white;")
        self.max_participants_label.setObjectName("max_participants_label")
        self.venue_label = QtWidgets.QLabel(self.main_frame)
        self.venue_label.setGeometry(QtCore.QRect(60, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.venue_label.setFont(font)
        self.venue_label.setStyleSheet("border: none;\n"
"color: white;")
        self.venue_label.setObjectName("venue_label")
        self.short_description_label = QtWidgets.QLabel(self.main_frame)
        self.short_description_label.setGeometry(QtCore.QRect(60, 470, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.short_description_label.setFont(font)
        self.short_description_label.setStyleSheet("border: none;\n"
"color: white;")
        self.short_description_label.setObjectName("short_description_label")
        self.description_label = QtWidgets.QLabel(self.main_frame)
        self.description_label.setGeometry(QtCore.QRect(430, 390, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.description_label.setFont(font)
        self.description_label.setStyleSheet("border: none;\n"
"color: white;")
        self.description_label.setObjectName("description_label")
        self.time_pick = QtWidgets.QTimeEdit(self.main_frame)
        self.time_pick.setGeometry(QtCore.QRect(580, 180, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.time_pick.setFont(font)
        self.time_pick.setStyleSheet("color: white;")
        self.time_pick.setAlignment(QtCore.Qt.AlignCenter)
        self.time_pick.setObjectName("time_pick")
        self.brochure_button = QtWidgets.QPushButton(self.main_frame)
        self.brochure_button.setGeometry(QtCore.QRect(860, 250, 321, 201))
        self.brochure_button.setStyleSheet("border-radius: 10px;")
        self.brochure_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Downloads/Lovepik_com-400278510-symbolic-linear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brochure_button.setIcon(icon)
        self.brochure_button.setIconSize(QtCore.QSize(60, 60))
        self.brochure_button.setObjectName("brochure_button")
        self.new_training_name = QtWidgets.QLabel(self.main_frame)
        self.new_training_name.setGeometry(QtCore.QRect(60, 180, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_training_name.setFont(font)
        self.new_training_name.setStyleSheet("borde: 1px solid white;\n"
"color: black;\n"
"background: white;\n"
"border-radius: 10px;")
        self.new_training_name.setText("")
        self.new_training_name.setObjectName("new_training_name")
        self.cost = QtWidgets.QLabel(self.main_frame)
        self.cost.setGeometry(QtCore.QRect(60, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cost.setFont(font)
        self.cost.setStyleSheet("borde: 1px solid white;\n"
"color: black;\n"
"background: white;\n"
"border-radius: 10px;")
        self.cost.setText("")
        self.cost.setObjectName("cost")
        self.description = QtWidgets.QLabel(self.main_frame)
        self.description.setGeometry(QtCore.QRect(430, 440, 371, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.description.setFont(font)
        self.description.setStyleSheet("borde: 1px solid white;\n"
"color: black;\n"
"background: white;\n"
"border-radius: 10px;")
        self.description.setText("")
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.short_description = QtWidgets.QLabel(self.main_frame)
        self.short_description.setGeometry(QtCore.QRect(60, 510, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.short_description.setFont(font)
        self.short_description.setStyleSheet("borde: 1px solid white;\n"
"color: black;\n"
"background: white;\n"
"border-radius: 10px;")
        self.short_description.setText("")
        self.short_description.setWordWrap(True)
        self.short_description.setObjectName("short_description")
        self.max_participants = QtWidgets.QLabel(self.main_frame)
        self.max_participants.setGeometry(QtCore.QRect(220, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_participants.setFont(font)
        self.max_participants.setStyleSheet("borde: 1px solid white;\n"
"color: black;\n"
"background: white;\n"
"border-radius: 10px;")
        self.max_participants.setText("")
        self.max_participants.setObjectName("max_participants")
        self.venue = QtWidgets.QLabel(self.main_frame)
        self.venue.setGeometry(QtCore.QRect(60, 290, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.venue.setFont(font)
        self.venue.setStyleSheet("borde: 1px solid white;\n"
"color: black;\n"
"background: white;\n"
"border-radius: 10px;")
        self.venue.setText("")
        self.venue.setObjectName("venue")
        self.create_button = QtWidgets.QPushButton(self.main_frame)
        self.create_button.setGeometry(QtCore.QRect(939, 600, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"background: #008287;")
        self.create_button.setObjectName("create_button")
        self.cancel_button = QtWidgets.QPushButton(self.main_frame)
        self.cancel_button.setGeometry(QtCore.QRect(1060, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"background: #008287;")
        self.cancel_button.setObjectName("cancel_button")
        self.department_pick = QtWidgets.QComboBox(self.main_frame)
        self.department_pick.setGeometry(QtCore.QRect(430, 290, 291, 41))
        self.department_pick.setObjectName("department_pick")
        self.check_box = QtWidgets.QCheckBox(self.main_frame)
        self.check_box.setGeometry(QtCore.QRect(430, 350, 301, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_box.setFont(font)
        self.check_box.setStyleSheet("border: none;\n"
"color: white;")
        self.check_box.setObjectName("check_box")
        self.horizontalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "New Training"))
        self.training_name_label.setText(_translate("MainWindow", "Training Name"))
        self.cost_label.setText(_translate("MainWindow", "Cost Per Pax"))
        self.datetime_label.setText(_translate("MainWindow", "Date & Time"))
        self.department_label.setText(_translate("MainWindow", "Department"))
        self.brochure_label.setText(_translate("MainWindow", "Brochure"))
        self.max_participants_label.setText(_translate("MainWindow", "Max Participants"))
        self.venue_label.setText(_translate("MainWindow", "Venue"))
        self.short_description_label.setText(_translate("MainWindow", "Short Description"))
        self.description_label.setText(_translate("MainWindow", "Description"))
        self.time_pick.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.create_button.setText(_translate("MainWindow", "Create"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.check_box.setText(_translate("MainWindow", "Add participants by department"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
