# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color:rgba(2, 65, 118, 200);\n"
"}")
        self.Loginframe = QtWidgets.QWidget(Form)
        self.Loginframe.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.Loginframe.setStyleSheet("background-color:rgba(16, 30, 41 240)")
        self.Loginframe.setObjectName("Loginframe")
        self.email_input = QtWidgets.QLineEdit(self.Loginframe)
        self.email_input.setGeometry(QtCore.QRect(515, 370, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_input.setFont(font)
        self.email_input.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.email_input.setObjectName("email_input")
        self.password_input = QtWidgets.QLineEdit(self.Loginframe)
        self.password_input.setGeometry(QtCore.QRect(515, 450, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.login_btn = QtWidgets.QPushButton(self.Loginframe)
        self.login_btn.setGeometry(QtCore.QRect(515, 530, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255) ;\n"
"background-color: rgb(125, 203, 227);\n"
"selection-background-color: rgb(172, 224, 249);\n"
"border-radius: 5px;\n"
"")
        self.login_btn.setCheckable(False)
        self.login_btn.setDefault(False)
        self.login_btn.setObjectName("login_btn")
        self.label = QtWidgets.QLabel(self.Loginframe)
        self.label.setGeometry(QtCore.QRect(515, 50, 250, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 250))
        self.label.setMaximumSize(QtCore.QSize(250, 250))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("9750963.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.email_input.setPlaceholderText(_translate("Form", "  Email"))
        self.password_input.setPlaceholderText(_translate("Form", "  Password"))
        self.login_btn.setText(_translate("Form", "L o g   I n"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
