from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


connect = sqlite3.connect('StaffTrainingSystem')
cursor = connect.cursor()


class Profile(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setMinimumSize(QtCore.QSize(960, 540))
        MainWindow.setMaximumSize(QtCore.QSize(960, 540))
        MainWindow.setStyleSheet("background-color: #696969;")

        # should remove later after combine login page
        self.email = "test"
        self.password = 123123

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(960, 540))
        self.centralwidget.setMaximumSize(QtCore.QSize(960, 540))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")

        # Title for the page
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(70, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setStyleSheet("color: white;")
        self.header.setObjectName("header")
        # page frame
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 90, 901, 421))
        self.frame.setStyleSheet("border: 1px solid white;\nborder-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # display gender
        self.gender_label = QtWidgets.QLabel(self.frame)
        self.gender_label.setGeometry(QtCore.QRect(382, 160, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setStyleSheet("color: white;\nborder: none;")
        self.gender_label.setObjectName("gender_label")
        # display department
        self.department_db = QtWidgets.QLabel(self.frame)
        self.department_db.setGeometry(QtCore.QRect(510, 350, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        # user details from db
        self.department_db.setFont(font)
        self.department_db.setStyleSheet("color: white;\nborder: none;")
        self.department_db.setText("")
        self.department_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.department_db.setObjectName("department_db")
        self.gender_db = QtWidgets.QLabel(self.frame)
        self.gender_db.setGeometry(QtCore.QRect(510, 160, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gender_db.setFont(font)
        self.gender_db.setStyleSheet("color: white;\nborder: none;")
        self.gender_db.setText("")
        self.gender_db.setObjectName("gender_db")
        # display profile image
        self.profile = QtWidgets.QLabel(self.frame)
        self.profile.setGeometry(QtCore.QRect(100, 110, 188, 188))
        self.profile.setStyleSheet("border: none;")
        self.profile.setText("")
        self.profile.setPixmap(QtGui.QPixmap("profile.png"))
        self.profile.setScaledContents(True)
        self.profile.setObjectName("profile")
        # display email
        self.email_label = QtWidgets.QLabel(self.frame)
        self.email_label.setGeometry(QtCore.QRect(400, 210, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("color: white;\nborder: none;")
        self.email_label.setObjectName("email_label")
        # display phone
        self.phone_label = QtWidgets.QLabel(self.frame)
        self.phone_label.setGeometry(QtCore.QRect(390, 260, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.phone_label.setFont(font)
        self.phone_label.setStyleSheet("color: white;\nborder: none;")
        self.phone_label.setObjectName("phone_label")
        # user details from db
        self.role_db = QtWidgets.QLabel(self.frame)
        self.role_db.setGeometry(QtCore.QRect(510, 304, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.role_db.setFont(font)
        self.role_db.setStyleSheet("color: white;\nborder: none;")
        self.role_db.setText("")
        self.role_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.role_db.setObjectName("role_db")
        self.phone_db = QtWidgets.QLabel(self.frame)
        self.phone_db.setGeometry(QtCore.QRect(510, 260, 151, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phone_db.setFont(font)
        self.phone_db.setStyleSheet("color: white;\nborder: none;")
        self.phone_db.setText("")
        self.phone_db.setObjectName("phone_db")
        self.name_db = QtWidgets.QLabel(self.frame)
        self.name_db.setGeometry(QtCore.QRect(510, 50, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_db.setFont(font)
        self.name_db.setStyleSheet("color: white;\nborder: none;")
        self.name_db.setText("")
        self.name_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name_db.setObjectName("name_db")
        self.name_label = QtWidgets.QLabel(self.frame)
        self.name_label.setGeometry(QtCore.QRect(400, 54, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        # display name
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color: white;\nborder: none;")
        self.name_label.setObjectName("name_label")
        # display role
        self.role_label = QtWidgets.QLabel(self.frame)
        self.role_label.setGeometry(QtCore.QRect(410, 310, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.role_label.setFont(font)
        self.role_label.setStyleSheet("color: white;\nborder: none;")
        self.role_label.setObjectName("role_label")
        # display department
        self.department_label = QtWidgets.QLabel(self.frame)
        self.department_label.setGeometry(QtCore.QRect(340, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.department_label.setFont(font)
        self.department_label.setStyleSheet("color: white;\nborder: none;")
        self.department_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.department_label.setObjectName("department_label")
        # user details from db
        self.email_db = QtWidgets.QLabel(self.frame)
        self.email_db.setGeometry(QtCore.QRect(510, 204, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_db.setFont(font)
        self.email_db.setStyleSheet("color: white;\nborder: none;")
        self.email_db.setText("")
        self.email_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.email_db.setObjectName("email_db")
        # display id
        self.staff_id_label = QtWidgets.QLabel(self.frame)
        self.staff_id_label.setGeometry(QtCore.QRect(376, 110, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.staff_id_label.setFont(font)
        self.staff_id_label.setStyleSheet("color: white;\nborder: none;")
        self.staff_id_label.setObjectName("staff_id_label")
        self.staff_id_db = QtWidgets.QLabel(self.frame)
        self.staff_id_db.setGeometry(QtCore.QRect(510, 110, 351, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.staff_id_db.setFont(font)
        self.staff_id_db.setStyleSheet("color: white;\nborder: none;")
        self.staff_id_db.setText("")
        self.staff_id_db.setObjectName("staff_id_db")
        # calling the user details from db and set it in these variable
        cursor.execute("SELECT e.employeeID, e.name, e.gender, e.phone_no, e.role, d.departmentName FROM "
                       "employee e, department d WHERE e.departmentID=d.departmentID AND e.email=?", (self.email,))
        info = cursor.fetchone()
        self.staff_id_db.setText(str(info[0]))
        self.name_db.setText(info[1])
        self.gender_db.setText(info[2])
        self.email_db.setText(self.email)
        self.phone_db.setText(str(info[3]))
        self.role_db.setText(info[4])
        self.department_db.setText(info[5])
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "User Profile"))
        self.gender_label.setText(_translate("MainWindow", "Gender:"))
        self.email_label.setText(_translate("MainWindow", "Email:"))
        self.phone_label.setText(_translate("MainWindow", "Phone:"))
        self.name_label.setText(_translate("MainWindow", "Name:"))
        self.role_label.setText(_translate("MainWindow", "Role:"))
        self.department_label.setText(_translate("MainWindow", "Department:"))
        self.staff_id_label.setText(_translate("MainWindow", "Staff ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Profile()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
